version: "3"

services:

    # mysql:
    #     image: mysql:5.7
    #     container_name: pythonFirst_mysql
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     restart: always
    #     ports:
    #         - 3311:3306
    #     environment:
    #         MYSQL_ROOT_PASSWORD: secret

    app:
        build:
            context: .
        volumes:
            - ./app:/app
        container_name: pythonAI
        restart: always
        ports:
            - 8091:80
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8091"
        # depends_on:
        #     - mysql
